name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      working-directory: microservice/omdb
      GO111MODULE: on
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
  
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name : install protobuf compiler
      run : |
        sudo apt-get install -y protobuf-compiler 
        
    - name : add to PATH
      run : |
        PATH="$PATH:$(go env GOPATH)/bin"
    
    - name : install protoc
      working-directory: ${{env.working-directory}}
      run : |
        go get google.golang.org/protobuf/cmd/protoc-gen-go google.golang.org/grpc/cmd/protoc-gen-go-grpc
        
    - name: Get dependencies
      working-directory: ${{env.working-directory}}
      run: |
        make init
        
    - name: Build proto
      working-directory: ${{env.working-directory}}
      run: |
        protoc --go_out=. \
        --go-grpc_out=. \
        proto/omdb.proto
        
    - name: Test
      working-directory: ${{env.working-directory}}
      run: go test -v ./...
        
    - name: Build
      working-directory: ${{env.working-directory}}
      run: go build -v ./...

    
