name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    
    - name : install protobuf compiler
      run : |
        sudo apt-get install -y protobuf-compiler
        
    - name : add to PATH
      run : |
        PATH="$PATH:$(go env GOPATH)/bin"
    
    - name : install protoc
      run : |
        go get google.golang.org/protobuf/cmd/protoc-gen-go google.golang.org/grpc/cmd/protoc-gen-go-grpc
        
    - name: Get dependencies & build proto
      run: |
        cd microservice/omdb
        make init
        make gen
        
    - name: Test
      run: go test -v ./...
        
    - name: Build
      run: go build -v ./...

    
