name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      working-directory: microservice/omdb
      GO111MODULE: on
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
  
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Proto compile golang
      uses: kubitre/proto_action@v1.2
      with:
        # proto file places
        dir_with_proto_name: proto
        # path to your generated contracts
        path_generated: .
        
    - name: Test
      working-directory: ${{env.working-directory}}
      run: go test -v ./...
        
    - name: Build
      working-directory: ${{env.working-directory}}
      run: go build -v ./...

    
